package com.example.musicmanager.database.models

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents an album entity in the database.
 * This class is annotated with Room annotations to define the table structure.
 *
 * @property id The unique identifier for the album. Auto-generated by the database.
 * @property name The name of the album.
 */
@Entity(tableName = "Albums")
data class Album(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
)
