package com.example.musicmanager.database.models

import androidx.room.Entity
import androidx.room.PrimaryKey
/**
 * Represents a song entity in the database.
 * This class is annotated with Room annotations to define the table structure.
 *
 * @property id The unique identifier for the song. Auto-generated by the database.
 * @property title The title of the song.
 * @property artist The artist of the song.
 * @property duration The duration of the song in seconds.
 * @property pathToFile The file path where the song is stored.
 */
@Entity(tableName = "Songs")
data class Song(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val artist: String,
    val duration: Int,
    val pathToFile: String
)